server:
  port: 8086
  tomcat:
    threads:
      max: 200
spring:
  application:
    name: pay-service
  rabbitmq:
    host: ${hm.db.host} # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /  # 虚拟主机
    username: itheima # 用户名
    password: 123321 # 密码
    connection-timeout: 1s
    publisher-confirm-type: correlated
    # correlated MQ异步回调方法返回绘制消息
    # simple 同步阻塞等待MQ回执消息
    publisher-returns: true
    active: dev
  datasource:
    url: jdbc:mysql://${hm.db.host}:3306/hm-pay?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hm.db.pw}
  cloud:
    nacos:
      server-addr: ${hm.db.host}:8848
mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
knife4j:
  enable: true
  openapi:
    title: 黑马商城山支付接口文档
    description: "黑马商城山支付接口文档"
    email: zhanghuyi@itcast.cn
    concat: 虎哥
    url: https://www.itcast.cn
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.hmall.pay.controller
feign:
  okhttp:
    enabled: true
